Fixes PR links on downloads 404ing
PaperMC/papermc.io pull request #134
Opened 2021-12-10 08:47 UTC by AffectedArc07

Untested and webedited because I dont have a devenv on hand, and I am patching log4J instances.

Currently, the PR links on downloads point to GitHub issues
![image](https://user-images.githubusercontent.com/25063394/145544713-cd51f956-4ed1-4737-8429-b9016544c60e.png)

This used to work, however, it doesn't anymore.
![image](https://user-images.githubusercontent.com/25063394/145544759-6c5bb799-bdcf-4275-8eb9-5e8d27165c65.png)

2021-12-10 08:51 UTC, kennytv requested changes
And what if a commit message actually links an issue?

2021-12-10 08:52 UTC, AffectedArc07 commented
> And what if a commit message actually links an issue?

Unsure of how we can go about that. Assuming this is a commit message (seems to be), the numbers prefixed with `fixes` or other terminology like that could direct to issues maybe?

I am not experienced with Twig/Whatever framework this is using (even though the thing I modified is pure JS, so I may be able to make it work, albeit in a scuffed way).

What way would you recommend going about this?

2021-12-10 08:55 UTC, kennytv commented
It might be worth checking if that is a GH bug at the moment, considering `issue` used to redirect to `pull` if it was a pull request... the same is still true the other way around, so I somehow doubt that this is an intentional change by them

2021-12-10 08:56 UTC, AffectedArc07 commented
> It might be worth checking if that is a GH bug at the moment, considering `issue` used to redirect to `pull` if it was a pull request... the same is still true the other way around, so I somehow doubt that this is an intentional change by them

I feel like its more GitHub deprecating stuff, as it seems half-unintended anyway? Unsure.

2021-12-13 02:56 UTC, Chew commented
I can't imagine this being intentional since, when we tested, the redirect works fine _when logged out_. Additionally, /pulls redirect to /issues fine. I'm surprised it's not either fixed or fully removed yet.

2021-12-13 03:09 UTC, sulu5890 commented
https://github.com/github/feedback/discussions/8623

2021-12-13 18:53 UTC, sulu5890 commented
GitHub has rolled back the change causing this.

2021-12-13 18:53 UTC, closed without merging