Re-add legacy builds with log4j patches
PaperMC/papermc.io pull request #144
Opened 2021-12-12 15:31 UTC by clrxbl

2021-12-12 15:33 UTC, electronicboy commented
No from me unless there is a mechanism where people have to explicitly acknowledge that these builds are unsupported in every form, shape, or manner; the string I talked about was only 50% of a gag. people seem to just skip past all of the reading aspect, so, having an action they have to explicitly take, especially if it's one where they have to type it, at least for me, is a massive win

2021-12-12 15:39 UTC, kennytv commented
I'd like for that to be a lite version of, so people **really** know: https://protocol.support/old/ ψ(._. )>

2021-12-12 15:43 UTC, kennytv submitted a review, later dismissed
(Properly blocking, really want to see that *actually* happen in a similar way where you have to type or select one or two options/sentences acknowledging you won't get support. But that'll have to be more than just a checkbox)

2021-12-12 15:44 UTC, NoahvdAa commented
I prefer this solution:

![](https://i.noah.pm/2AwDP5.gif)

In all seriousness, something like kenny linked (but slightly less extreme) is probably a good solution. It'll allow users that *really, really* want to download legacy builds to download them, and at the same time hopefully keep people from using legacy versions more. Maybe have them type a sentence? (looks like kenny mentioned this right before I clicked comment)

2021-12-12 15:55 UTC, Phoenix616 commented
I feel like simply putting in a check box besides a "I acknowledge that by downloading this build I will receive no support and that running it might expose me to unpatched bugs and exploits." sentence should be enough.

Going through extreme lengths to download something will at best just get people to ignore what is said there or at worst make them go to a third party site which distributed jars with questionable content. At least with the checkbox there is a clear user action required (which at least seems to hold up legally). Will it stop people from using those versions? No. But so doesn't any other method which still lets one download it.

2021-12-12 15:56 UTC, electronicboy commented
We've had the message saying that we offer 0 support for these versions and we still get the expectation of support. We don't care if people use them, we're just tired of the expectation that they're still supported because we offer them

2021-12-12 15:57 UTC, kennytv commented
A checkbox would work just as well as any checklist people tick in GitHub issues saying "I'm on latest, I've followed the issue template", especially with the kind of people asking for legacy support

2021-12-12 16:04 UTC, Phoenix616 commented
> A checkbox would work just as well as any checklist people tick in GitHub issues saying "I'm on latest, I've followed the issue template", especially with the kind of people asking for legacy support. It's not like the legacy page is the main attraction Paper has to offer that thousands of people use on a daily basis

It will work as well as any other method which is basically that it doesn't. The only way to completely distance Paper from the old versions is to not offer those jars in the first place on the website itself and live with the fact that people are going to use random sources.

2021-12-12 17:16 UTC, clrxbl commented
I have added my magnum opus in web development:

https://user-images.githubusercontent.com/28601081/145722390-5d65f89c-0690-4b4b-b5c0-9de9874fe451.mp4

2021-12-12 17:21 UTC, electronicboy commented
![image](https://user-images.githubusercontent.com/1228900/145722554-508ac889-8b6d-431a-ad92-f95a86348e38.png)

2021-12-12 17:29 UTC, NoahvdAa commented on src/js/legacy.js
> +  if (! checkValue("quiz-1", "2")) {
Can't we put all of these into one if statement?

2021-12-12 17:34 UTC, JRoy commented on src/js/legacy.js
> +  if (! checkValue("quiz-1", "2")) {
it's impossible, could never be done

2021-12-12 17:35 UTC, NoahvdAa commented on src/js/legacy.js
> +  if (! checkValue("quiz-1", "2")) {
Thanks for checking that for me, sorry for making impossible requests :(

2021-12-12 17:35 UTC, clrxbl commented on src/js/legacy.js
> +  if (! checkValue("quiz-1", "2")) {
I've compacted the quiz answer stuff into one else if statement but other than that, don't think so?

2021-12-12 17:37 UTC, NoahvdAa commented on src/js/legacy.js
> +  if (! checkValue("quiz-1", "2")) {
You can compact it into a single if statement using the lovely OR operator:
```js
if (!checkValue("quiz-1", "2") || !checkValue("quiz-2", "2") || !checkValue("quiz-3", "2") || !checkValue("quiz-4", "4")) {
       failed = true;
}
```

2021-12-12 17:38 UTC, clrxbl commented on src/js/legacy.js
> +  if (! checkValue("quiz-1", "2")) {
Doesn't that become ugly if there's a lot more than 4 questions? (Unsure if the questions we have right now are the ones we'll want to be asking at the moment)

2021-12-12 17:41 UTC, NoahvdAa commented on src/js/legacy.js
> +  if (! checkValue("quiz-1", "2")) {
IMO this is a lot cleaner than having multiple lines of nearly identical if statements

2021-12-12 17:43 UTC, clrxbl commented on src/js/legacy.js
> +  if (! checkValue("quiz-1", "2")) {
I've gone with your route for now at least, thanks.

2021-12-12 18:02 UTC, kennytv approved these changes

2021-12-12 18:11 UTC, mbax commented
Why are the questions *so incredibly tiny*?

2021-12-12 18:12 UTC, clrxbl commented
> Why are the questions _so incredibly tiny_?

Already resolved
![image](https://user-images.githubusercontent.com/28601081/145724312-efae746d-0571-4d56-9c3e-40c7bb53a7d3.png)

2021-12-12 18:19 UTC, NotMyFault requested changes
![](https://i.imgur.com/MmG3uzb.png)
The font is barely visible if you're using different themes.

2021-12-12 18:26 UTC, clrxbl commented
> ![](https://camo.githubusercontent.com/878e5c8efa333c4fdf50f389113d25fd529e0004bcd3897573090a22a96e1456/68747470733a2f2f692e696d6775722e636f6d2f4d6d4733757a622e706e67) The font is barely visible if you're using different themes.

I forgot that the Paper site can be viewed in light mode since there's no light/dark mode toggle on the site. Fixed.

2021-12-12 18:29 UTC, NotMyFault commented
> > ![](https://camo.githubusercontent.com/878e5c8efa333c4fdf50f389113d25fd529e0004bcd3897573090a22a96e1456/68747470733a2f2f692e696d6775722e636f6d2f4d6d4733757a622e706e67) The font is barely visible if you're using different themes.
> 
> I forgot that the Paper site can be viewed in light mode since there's no light/dark mode toggle on the site. Fixed.

Looking better now, thanks.

2021-12-12 18:42 UTC, Cryptite commented
> we're just tired of the expectation that they're still supported because we offer them

To be fair this is an eternal, and permanent constant. This will never change. As long as you have the CYA bit anywhere, you can always point to it.

2021-12-12 18:55 UTC, JRoy approved these changes
works as intended and uses non-free software

2021-12-13 00:31 UTC, merged

2021-12-13 00:57 UTC, TwoLeggedCat commented on src/legacy.twig
> +          You may be <strong>kicked or muted</strong> when asking for support on our Discord.
Bit late to the party, but perhaps this (and the form) should mention the forums as well?

2021-12-13 01:20 UTC, MWHunter commented
Failing the quiz multiple times makes the countdown faster.