Add a page to quickly find the Maven coordinates and snippets for Maven and Gradle
PaperMC/papermc.io pull request #72
Opened 2021-02-25 11:41 UTC by simpleauthority

This PR adds a page for developers to quickly find and copy snippets for Maven and Gradle to access the Paper API in their plugins.

It uses a minified form of highlight.js with support for XML and Groovy only to provide a repository and dependency snippet for both Maven and Gradle.

It also hits the Paper HTTP API to determine the latest version for the Maven/Gradle snippets, so it should be almost maintenance-less save for HTTP API changes. 

One caveat: I am getting the latest version group and then the latest version within that, and then simply concatenating `-R0.1-SNAPSHOT`...while this will work for the first release, it won't work for later ones. However, at the moment the API does not return the latest artifact. If it did, we could change this.

Here's how it looks...

Homepage:
![index](https://static.jacobandersen.dev/shared/💊🌥🥳🦅😡.png)

Navbar:
![navbar](https://static.jacobandersen.dev/shared/🕳🧹🛥😋🌭.png)

Actual page (zoomed out, located at `/using-the-api`):
![page](https://static.jacobandersen.dev/shared/🐶🍧🤔🌮😦.png)

Thoughts? Changes?

2021-02-25 11:42 UTC, simpleauthority commented
Also, closes #71.

2021-02-25 17:04 UTC, MiniDigger commented
since we already had a discussion on the paper repo for the readme, to add gradle kotlin dsl, what do you think about a tab layout with 3 tabs for maven groovy and kotlin?

2021-02-25 20:45 UTC, kashike requested changes

2021-02-25 20:45 UTC, kashike commented on src/js/highlight.min.js
> +/*
Why are we hosting this instead of just using a CDN?

2021-02-25 22:52 UTC, simpleauthority commented on src/js/highlight.min.js
> +/*
@kashike Because this is a custom highlight.js package. The CDN version does not include Groovy, only a subset containing 36 of the most common languages. XML/HTML is included in that, but not Groovy. So this file contains JUST XML/HTML and Groovy support and no others.

2021-02-25 22:52 UTC, simpleauthority commented
> 
> 
> since we already had a discussion on the paper repo for the readme, to add gradle kotlin dsl, what do you think about a tab layout with 3 tabs for maven groovy and kotlin?

good idea, will check it out

2021-02-25 23:10 UTC, kashike commented on src/js/highlight.min.js
> +/*
Perhaps add a comment to the top of this file with this information?

2021-02-25 23:42 UTC, simpleauthority commented on src/js/highlight.min.js
> +/*
Will do

2021-02-26 07:32 UTC, simpleauthority commented
We are now looking like this: https://www.youtube.com/watch?v=3DNmP2Ta-fA

2021-03-05 09:03 UTC, kashike approved these changes

2021-03-05 09:03 UTC, merged